#!/usr/bin/env python
# -*- coding: utf-8 -*-

LANGS = (( 'aar', 'aa', "Afar", "afar" ),
         ( 'abk', 'ab', "Abkhazian", "abkhaze" ),
         ( 'ace', None, "Achinese", "aceh" ),
         ( 'ach', None, "Acoli", "acoli" ),
         ( 'ada', None, "Adangme", "adangme" ),
         ( 'ady', None, "Adyghe; Adygei", "adyghé" ),
         ( 'afa', None, "Afro-Asiatic languages", "afro-asiatiques, langues" ),
         ( 'afh', None, "Afrihili", "afrihili" ),
         ( 'afr', 'af', "Afrikaans", "afrikaans" ),
         ( 'ain', None, "Ainu", "aïnou" ),
         ( 'aka', 'ak', "Akan", "akan" ),
         ( 'akk', None, "Akkadian", "akkadien" ),
         ( 'alb', 'sq', "Albanian", "albanais" ),
         ( 'ale', None, "Aleut", "aléoute" ),
         ( 'alg', None, "Algonquian languages", "algonquines, langues" ),
         ( 'alt', None, "Southern Altai", "altai du Sud" ),
         ( 'amh', 'am', "Amharic", "amharique" ),
         ( 'ang', None, "English, Old (ca.450-1100)", "anglo-saxon (ca.450-1100)" ),
         ( 'anp', None, "Angika", "angika" ),
         ( 'apa', None, "Apache languages", "apaches, langues" ),
         ( 'ara', 'ar', "Arabic", "arabe" ),
         ( 'arc', None, "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)", "araméen d'empire (700-300 BCE)" ),
         ( 'arg', 'an', "Aragonese", "aragonais" ),
         ( 'arm', None, "Armenian", "arménien", "Armenisch" ),
         ( 'arn', None, "Mapudungun; Mapuche", "mapudungun; mapuche; mapuce" ),
         ( 'arp', None, "Arapaho", "arapaho" ),
         ( 'art', None, "Artificial languages", "artificielles, langues" ),
         ( 'arw', None, "Arawak", "arawak" ),
         ( 'asm', 'as', "Assamese", "assamais" ),
         ( 'ast', None, "Asturian; Bable; Leonese; Asturleonese", "asturien; bable; léonais; asturoléonais" ),
         ( 'ath', None, "Athapascan languages", "athapascanes, langues" ),
         ( 'aus', None, "Australian languages", "australiennes, langues" ),
         ( 'ava', 'av', "Avaric", "avar" ),
         ( 'ave', 'ae', "Avestan", "avestique" ),
         ( 'awa', None, "Awadhi", "awadhi" ),
         ( 'aym', 'ay', "Aymara", "aymara" ),
         ( 'aze', 'az', "Azerbaijani", "azéri" ),
         ( 'bad', None, "Banda languages", "banda, langues" ),
         ( 'bai', None, "Bamileke languages", "bamiléké, langues" ),
         ( 'bak', 'ba', "Bashkir", "bachkir" ),
         ( 'bal', None, "Baluchi", "baloutchi" ),
         ( 'bam', 'bm', "Bambara", "bambara" ),
         ( 'ban', None, "Balinese", "balinais" ),
         ( 'baq', 'eu', "Basque", "basque" ),
         ( 'bas', None, "Basa", "basa" ),
         ( 'bat', None, "Baltic languages", "baltes, langues" ),
         ( 'bej', None, "Beja; Bedawiyet", "bedja" ),
         ( 'bel', 'be', "Belarusian", "biélorusse" ),
         ( 'bem', None, "Bemba", "bemba" ),
         ( 'ben', 'bn', "Bengali", "bengali" ),
         ( 'ber', None, "Berber languages", "berbères, langues" ),
         ( 'bho', None, "Bhojpuri", "bhojpuri" ),
         ( 'bih', 'bh', "Bihari languages", "langues biharis" ),
         ( 'bik', None, "Bikol", "bikol" ),
         ( 'bin', None, "Bini; Edo", "bini; edo" ),
         ( 'bis', 'bi', "Bislama", "bichlamar" ),
         ( 'bla', None, "Siksika", "blackfoot" ),
         ( 'bnt', None, "Bantu languages", "bantou, langues" ),
         ( 'tib', 'bo', "Tibetan", "tibétain" ),
         ( 'bos', 'bs', "Bosnian", "bosniaque" ),
         ( 'bra', None, "Braj", "braj" ),
         ( 'bre', 'br', "Breton", "breton" ),
         ( 'btk', None, "Batak languages", "batak, langues" ),
         ( 'bua', None, "Buriat", "bouriate" ),
         ( 'bug', None, "Buginese", "bugi" ),
         ( 'bul', 'bg', "Bulgarian", "bulgare" ),
         ( 'bur', 'my', "Burmese", "birman" ),
         ( 'byn', None, "Blin; Bilin", "blin; bilen" ),
         ( 'cad', None, "Caddo", "caddo" ),
         ( 'cai', None, "Central American Indian languages", "amérindiennes de l'Amérique centrale, langues" ),
         ( 'car', None, "Galibi Carib", "karib; galibi; carib" ),
         ( 'cat', 'ca', "Catalan; Valencian", "catalan; valencien" ),
         ( 'cau', None, "Caucasian languages", "caucasiennes, langues" ),
         ( 'ceb', None, "Cebuano", "cebuano" ),
         ( 'cel', None, "Celtic languages", "celtiques, langues; celtes, langues" ),
         ( 'cze', 'cs', "Czech", "tchèque" ),
         ( 'cha', 'ch', "Chamorro", "chamorro" ),
         ( 'chb', None, "Chibcha", "chibcha" ),
         ( 'che', 'ce', "Chechen", "tchétchène" ),
         ( 'chg', None, "Chagatai", "djaghataï" ),
         ( 'chi', 'zh', "Chinese", "chinois" ),
         ( 'chk', None, "Chuukese", "chuuk" ),
         ( 'chm', None, "Mari", "mari" ),
         ( 'chn', None, "Chinook jargon", "chinook, jargon" ),
         ( 'cho', None, "Choctaw", "choctaw" ),
         ( 'chp', None, "Chipewyan; Dene Suline", "chipewyan" ),
         ( 'chr', None, "Cherokee", "cherokee" ),
         ( 'chu', 'cu', "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic", "slavon d'église; vieux slave; slavon liturgique; vieux bulgare" ),
         ( 'chv', 'cv', "Chuvash", "tchouvache" ),
         ( 'chy', None, "Cheyenne", "cheyenne" ),
         ( 'cmc', None, "Chamic languages", "chames, langues" ),
         ( 'cop', None, "Coptic", "copte" ),
         ( 'cor', 'kw', "Cornish", "cornique" ),
         ( 'cos', 'co', "Corsican", "corse" ),
         ( 'cpe', None, "Creoles and pidgins, English based", "créoles et pidgins basés sur l'anglais" ),
         ( 'cpf', None, "Creoles and pidgins, French-based", "créoles et pidgins basés sur le français" ),
         ( 'cpp', None, "Creoles and pidgins, Portuguese-based", "créoles et pidgins basés sur le portugais" ),
         ( 'cre', 'cr', "Cree", "cree" ),
         ( 'crh', None, "Crimean Tatar; Crimean Turkish", "tatar de Crimé" ),
         ( 'crp', None, "Creoles and pidgins", "créoles et pidgins" ),
         ( 'csb', None, "Kashubian", "kachoube" ),
         ( 'cus', None, "Cushitic languages", "couchitiques, langues" ),
         ( 'wel', 'cy', "Welsh", "gallois" ),
         ( 'cze', 'cs', "Czech", "tchèque" ),
         ( 'dak', None, "Dakota", "dakota" ),
         ( 'dan', 'da', "Danish", "danois" ),
         ( 'dar', None, "Dargwa", "dargwa" ),
         ( 'day', None, "Land Dayak languages", "dayak, langues" ),
         ( 'del', None, "Delaware", "delaware" ),
         ( 'den', None, "Slave (Athapascan)", "esclave (athapascan)" ),
         ( 'ger', 'de', "German", "allemand" ),
         ( 'dgr', None, "Dogrib", "dogrib" ),
         ( 'din', None, "Dinka", "dinka" ),
         ( 'div', 'dv', "Divehi; Dhivehi; Maldivian", "maldivien" ),
         ( 'doi', None, "Dogri", "dogri" ),
         ( 'dra', None, "Dravidian languages", "dravidiennes, langues" ),
         ( 'dsb', None, "Lower Sorbian", "bas-sorabe" ),
         ( 'dua', None, "Duala", "douala" ),
         ( 'dum', None, "Dutch, Middle (ca.1050-1350)", "néerlandais moyen (ca. 1050-1350)" ),
         ( 'dut', 'nl', "Dutch; Flemish", "néerlandais; flamand" ),
         ( 'dyu', None, "Dyula", "dioula" ),
         ( 'dzo', 'dz', "Dzongkha", "dzongkha" ),
         ( 'efi', None, "Efik", "efik" ),
         ( 'egy', None, "Egyptian (Ancient)", "égyptien" ),
         ( 'eka', None, "Ekajuk", "ekajuk" ),
         ( 'gre', 'el', "Greek, Modern (1453-)", "grec moderne (après 1453)" ),
         ( 'elx', None, "Elamite", "élamite" ),
         ( 'eng', 'en', "English", "anglais" ),
         ( 'enm', None, "English, Middle (1100-1500)", "anglais moyen (1100-1500)" ),
         ( 'epo', 'eo', "Esperanto", "espéranto" ),
         ( 'est', 'et', "Estonian", "estonien" ),
         ( 'baq', 'eu', "Basque", "basque" ),
         ( 'ewe', 'ee', 'Ewe', 'éwé' ),
         ( 'ewo', None, "Ewondo", "éwondo" ),
         ( 'fan', None, "Fang", "fang" ),
         ( 'fao', 'fo', "Faroese", "féroïen" ),
         ( 'per', 'fa', "Persian", "persan" ),
         ( 'fat', None, "Fanti", "fanti" ),
         ( 'fij', 'fj', "Fijian", "fidjien" ),
         ( 'fil', None, "Filipino; Pilipino", "filipino; pilipino" ),
         ( 'fin', 'fi', "Finnish", "finnois" ),
         ( 'fiu', None, "Finno-Ugrian languages", "finno-ougriennes, langues" ),
         ( 'fon', None, 'Fon', 'fon' ),
         ( 'fre', 'fr', "French", "français" ),
         ( 'fre', 'fr', "French", "français" ),
         ( 'frm', None, "French, Middle (ca.1400-1600)", "français moyen (1400-1600)" ),
         ( 'fro', None, "French, Old (842-ca.1400)", "français ancien (842-ca.1400)" ),
         ( 'frr', None, "Northern Frisian", "frison septentrional" ),
         ( 'frs', None, "Eastern Frisian", "frison oriental" ),
         ( 'fry', 'fy', "Western Frisian", "frison occidental" ),
         ( 'ful', 'ff', "Fulah", "peul" ),
         ( 'fur', None, "Friulian", "frioulan" ),
         ( 'gaa', None, 'Ga', 'ga' ),
         ( 'gay', None, "Gayo", "gayo" ),
         ( 'gba', None, "Gbaya", "gbaya" ),
         ( 'gem', None, "Germanic languages", "germaniques, langues" ),
         ( 'geo', 'ka', "Georgian", "géorgien" ),
         ( 'ger', 'de', "German", "allemand" ),
         ( 'gez', None, "Geez", "guèze" ),
         ( 'gil', None, "Gilbertese", "kiribati" ),
         ( 'gla', 'gd', "Gaelic; Scottish Gaelic", "gaélique; gaélique écossais" ),
         ( 'gle', 'ga', "Irish", "irlandais" ),
         ( 'glg', 'gl', "Galician", "galicien" ),
         ( 'glv', 'gv', "Manx", "manx; mannois" ),
         ( 'gmh', None, "German, Middle High (ca.1050-1500)", "allemand, moyen haut (ca. 1050-1500)" ),
         ( 'goh', None, "German, Old High (ca.750-1050)", "allemand, vieux haut (ca. 750-1050)" ),
         ( 'gon', None, "Gondi", "gond" ),
         ( 'gor', None, "Gorontalo", "gorontalo" ),
         ( 'got', None, "Gothic", "gothique" ),
         ( 'grb', None, "Grebo", "grebo" ),
         ( 'grc', None, "Greek, Ancient (to 1453)", "grec ancien (jusqu'à 1453)" ),
         ( 'gre', 'el', "Greek, Modern (1453-)", "grec moderne (après 1453)" ),
         ( 'grn', 'gn', "Guarani", "guarani" ),
         ( 'gsw', None, "Swiss German; Alemannic; Alsatian", "suisse alémanique; alémanique; alsacien" ),
         ( 'guj', 'gu', "Gujarati", "goudjrati" ),
         ( 'gwi', None, "Gwich'in", "gwich'in" ),
         ( 'hai', None, "Haida", "haida" ),
         ( 'hat', 'ht', "Haitian; Haitian Creole", "haïtien; créole haïtien" ),
         ( 'hau', 'ha', "Hausa", "haoussa" ),
         ( 'haw', None, "Hawaiian", "hawaïen" ),
         ( 'heb', 'he', "Hebrew", "hébreu" ),
         ( 'her', 'hz', "Herero", "herero" ),
         ( 'hil', None, "Hiligaynon", "hiligaynon" ),
         ( 'him', None, "Himachali languages; Western Pahari languages", "langues himachalis; langues paharis occidentales" ),
         ( 'hin', 'hi', "Hindi", "hindi" ),
         ( 'hit', None, "Hittite", "hittite" ),
         ( 'hmn', None, "Hmong; Mong", "hmong" ),
         ( 'hmo', 'ho', "Hiri Motu", "hiri motu" ),
         ( 'hrv', 'hr', "Croatian", "croate" ),
         ( 'hsb', None, "Upper Sorbian", "haut-sorabe" ),
         ( 'hun', 'hu', "Hungarian", "hongrois" ),
         ( 'hup', None, "Hupa", "hupa" ),
         ( 'arm', 'hy', "Armenian", "arménien" ),
         ( 'iba', None, "Iban", "iban" ),
         ( 'ibo', 'ig', "Igbo", "igbo" ),
         ( 'ice', 'is', "Icelandic", "islandais" ),
         ( 'ido', 'io', 'Ido', 'ido' ),
         ( 'iii', 'ii', "Sichuan Yi; Nuosu", "yi de Sichuan" ),
         ( 'ijo', None, "Ijo languages", "ijo, langues" ),
         ( 'iku', 'iu', "Inuktitut", "inuktitut" ),
         ( 'ile', 'ie', "Interlingue; Occidental", "interlingue" ),
         ( 'ilo', None, "Iloko", "ilocano" ),
         ( 'ina', 'ia', "Interlingua (International Auxiliary Language Association)", "interlingua (langue auxiliaire internationale)" ),
         ( 'inc', None, "Indic languages", "indo-aryennes, langues" ),
         ( 'ind', 'id', "Indonesian", "indonésien" ),
         ( 'ine', None, "Indo-European languages", "indo-européennes, langues" ),
         ( 'inh', None, "Ingush", "ingouche" ),
         ( 'ipk', 'ik', "Inupiaq", "inupiaq" ),
         ( 'ira', None, "Iranian languages", "iraniennes, langues" ),
         ( 'iro', None, "Iroquoian languages", "iroquoises, langues" ),
         ( 'ice', 'is', "Icelandic", "islandais" ),
         ( 'ita', 'it', "Italian", "italien" ),
         ( 'jav', 'jv', "Javanese", "javanais" ),
         ( 'jbo', None, "Lojban", "lojban" ),
         ( 'jpn', 'ja', "Japanese", "japonais" ),
         ( 'jpr', None, "Judeo-Persian", "judéo-persan" ),
         ( 'jrb', None, "Judeo-Arabic", "judéo-arabe" ),
         ( 'kaa', None, "Kara-Kalpak", "karakalpak" ),
         ( 'kab', None, "Kabyle", "kabyle" ),
         ( 'kac', None, "Kachin; Jingpho", "kachin; jingpho" ),
         ( 'kal', 'kl', "Kalaallisut; Greenlandic", "groenlandais" ),
         ( 'kam', None, "Kamba", "kamba" ),
         ( 'kan', 'kn', "Kannada", "kannada" ),
         ( 'kar', None, "Karen languages", "karen, langues" ),
         ( 'kas', 'ks', "Kashmiri", "kashmiri" ),
         ( 'geo', 'ka', "Georgian", "géorgien" ),
         ( 'kau', 'kr', "Kanuri", "kanouri" ),
         ( 'kaw', None, "Kawi", "kawi" ),
         ( 'kaz', 'kk', "Kazakh", "kazakh" ),
         ( 'kbd', None, "Kabardian", "kabardien" ),
         ( 'kha', None, "Khasi", "khasi" ),
         ( 'khi', None, "Khoisan languages", "khoïsan, langues" ),
         ( 'khm', 'km', "Central Khmer", "khmer central" ),
         ( 'kho', None, "Khotanese; Sakan", "khotanais; sakan" ),
         ( 'kik', 'ki', "Kikuyu; Gikuyu", "kikuyu" ),
         ( 'kin', 'rw', "Kinyarwanda", "rwanda" ),
         ( 'kir', 'ky', "Kirghiz; Kyrgyz", "kirghiz" ),
         ( 'kmb', None, "Kimbundu", "kimbundu" ),
         ( 'kok', None, "Konkani", "konkani" ),
         ( 'kom', 'kv', "Komi", 'kom' ),
         ( 'kon', 'kg', "Kongo", "kongo" ),
         ( 'kor', 'ko', "Korean", "coréen" ),
         ( 'kos', None, "Kosraean", "kosrae" ),
         ( 'kpe', None, "Kpelle", "kpellé" ),
         ( 'krc', None, "Karachay-Balkar", "karatchai balkar" ),
         ( 'krl', None, "Karelian", "carélien" ),
         ( 'kro', None, "Kru languages", "krou, langues" ),
         ( 'kru', None, "Kurukh", "kurukh" ),
         ( 'kua', 'kj', "Kuanyama; Kwanyama", "kuanyama; kwanyama" ),
         ( 'kum', None, "Kumyk", "koumyk" ),
         ( 'kur', 'ku', "Kurdish", "kurde" ),
         ( 'kut', None, "Kutenai", "kutenai" ),
         ( 'lad', None, "Ladino", "judéo-espagnol" ),
         ( 'lah', None, "Lahnda", "lahnda" ),
         ( 'lam', None, "Lamba", "lamba" ),
         ( 'lao', 'lo', 'Lao', 'lao' ),
         ( 'lat', 'la', "Latin", "latin" ),
         ( 'lav', 'lv', "Latvian", "letton" ),
         ( 'lez', None, "Lezghian", "lezghien" ),
         ( 'lim', 'li', "Limburgan; Limburger; Limburgish", "limbourgeois" ),
         ( 'lin', 'ln', "Lingala", "lingala" ),
         ( 'lit', 'lt', "Lithuanian", "lituanien" ),
         ( 'lol', None, "Mongo", "mongo" ),
         ( 'loz', None, "Lozi", "lozi" ),
         ( 'ltz', 'lb', "Luxembourgish; Letzeburgesch", "luxembourgeois" ),
         ( 'lua', None, "Luba-Lulua", "luba-lulua" ),
         ( 'lub', 'lu', "Luba-Katanga", "luba-katanga" ),
         ( 'lug', 'lg', "Ganda", "ganda" ),
         ( 'lui', None, "Luiseno", "luiseno" ),
         ( 'lun', None, "Lunda", "lunda" ),
         ( 'luo', None, "Luo (Kenya and Tanzania)", "luo (Kenya et Tanzanie)" ),
         ( 'lus', None, "Lushai", "lushai" ),
         ( 'mac', 'mk', "Macedonian", "macédonien" ),
         ( 'mad', None, "Madurese", "madourais" ),
         ( 'mag', None, "Magahi", "magahi" ),
         ( 'mah', 'mh', "Marshallese", "marshall" ),
         ( 'mai', None, "Maithili", "maithili" ),
         ( 'mak', None, "Makasar", "makassar" ),
         ( 'mal', 'ml', "Malayalam", "malayalam" ),
         ( 'man', None, "Mandingo", "mandingue" ),
         ( 'mao', 'mi', "Maori", "maori" ),
         ( 'map', None, "Austronesian languages", "austronésiennes, langues" ),
         ( 'mar', 'mr', "Marathi", "marathe" ),
         ( 'mas', None, "Masai", "massaï" ),
         ( 'may', 'ms', "Malay", "malais" ),
         ( 'mdf', None, "Moksha", "moksa" ),
         ( 'mdr', None, "Mandar", "mandar" ),
         ( 'men', None, "Mende", "mendé" ),
         ( 'mga', None, "Irish, Middle (900-1200)", "irlandais moyen (900-1200)" ),
         ( 'mic', None, "Mi'kmaq; Micmac", "mi'kmaq; micmac" ),
         ( 'min', None, "Minangkabau", "minangkabau" ),
         ( 'mis', None, "Uncoded languages", "langues non codées" ),
         ( 'mac', 'mk', "Macedonian", "macédonien" ),
         ( 'mkh', None, "Mon-Khmer languages", "môn-khmer, langues" ),
         ( 'mlg', 'mg', "Malagasy", "malgache" ),
         ( 'mlt', 'mt', "Maltese", "maltais" ),
         ( 'mnc', None, "Manchu", "mandchou" ),
         ( 'mni', None, "Manipuri", "manipuri" ),
         ( 'mno', None, "Manobo languages", "manobo, langues" ),
         ( 'moh', None, "Mohawk", "mohawk" ),
         ( 'mon', 'mn', "Mongolian", "mongol" ),
         ( 'mos', None, "Mossi", "moré" ),
         ( 'mao', 'mi', "Maori", "maori" ),
         ( 'may', 'ms', "Malay", "malais" ),
         ( 'mul', None, "Multiple languages", "multilingue" ),
         ( 'mun', None, "Munda languages", "mounda, langues" ),
         ( 'mus', None, "Creek", "muskogee" ),
         ( 'mwl', None, "Mirandese", "mirandais" ),
         ( 'mwr', None, "Marwari", "marvari" ),
         ( 'bur', 'my', "Burmese", "birman" ),
         ( 'myn', None, "Mayan languages", "maya, langues" ),
         ( 'myv', None, "Erzya", "erza" ),
         ( 'nah', None, "Nahuatl languages", "nahuatl, langues" ),
         ( 'nai', None, "North American Indian languages", "nord-amérindiennes, langues" ),
         ( 'nap', None, "Neapolitan", "napolitain" ),
         ( 'nau', 'na', "Nauru", "nauruan" ),
         ( 'nav', 'nv', "Navajo; Navaho", "navaho" ),
         ( 'nbl', 'nr', "Ndebele, South; South Ndebele", "ndébélé du Sud" ),
         ( 'nde', 'nd', "Ndebele, North; North Ndebele", "ndébélé du Nord" ),
         ( 'ndo', 'ng', "Ndonga", "ndonga" ),
         ( 'nds', None, "Low German; Low Saxon; German, Low; Saxon, Low", "bas allemand; bas saxon; allemand, bas; saxon, bas" ),
         ( 'nep', 'ne', "Nepali", "népalais" ),
         ( 'new', None, "Nepal Bhasa; Newari", "nepal bhasa; newari" ),
         ( 'nia', None, "Nias", "nias" ),
         ( 'nic', None, "Niger-Kordofanian languages", "nigéro-kordofaniennes, langues" ),
         ( 'niu', None, "Niuean", "niué" ),
         ( 'dut', 'nl', "Dutch; Flemish", "néerlandais; flamand" ),
         ( 'nno', 'nn', "Norwegian Nynorsk; Nynorsk, Norwegian", "norvégien nynorsk; nynorsk, norvégien" ),
         ( 'nob', 'nb', "Bokmål, Norwegian; Norwegian Bokmål", "norvégien bokmål" ),
         ( 'nog', None, "Nogai", "nogaï; nogay" ),
         ( 'non', None, "Norse, Old", "norrois, vieux" ),
         ( 'nor', 'no', "Norwegian", "norvégien" ),
         ( 'nqo', None, "N'Ko", "n'ko" ),
         ( 'nso', None, "Pedi; Sepedi; Northern Sotho", "pedi; sepedi; sotho du Nord" ),
         ( 'nub', None, "Nubian languages", "nubiennes, langues" ),
         ( 'nwc', None, "Classical Newari; Old Newari; Classical Nepal Bhasa", "newari classique" ),
         ( 'nya', 'ny', "Chichewa; Chewa; Nyanja", "chichewa; chewa; nyanja" ),
         ( 'nym', None, "Nyamwezi", "nyamwezi" ),
         ( 'nyn', None, "Nyankole", "nyankolé" ),
         ( 'nyo', None, "Nyoro", "nyoro" ),
         ( 'nzi', None, "Nzima", "nzema" ),
         ( 'oci', 'oc', "Occitan (post 1500)", "occitan (après 1500)" ),
         ( 'oji', 'oj', "Ojibwa", "ojibwa" ),
         ( 'ori', 'or', "Oriya", "oriya" ),
         ( 'orm', 'om', "Oromo", "galla" ),
         ( 'osa', None, "Osage", "osage" ),
         ( 'oss', 'os', "Ossetian; Ossetic", "ossète" ),
         ( 'ota', None, "Turkish, Ottoman (1500-1928)", "turc ottoman (1500-1928)" ),
         ( 'oto', None, "Otomian languages", "otomi, langues" ),
         ( 'paa', None, "Papuan languages", "papoues, langues" ),
         ( 'pag', None, "Pangasinan", "pangasinan" ),
         ( 'pal', None, "Pahlavi", "pahlavi" ),
         ( 'pam', None, "Pampanga; Kapampangan", "pampangan" ),
         ( 'pan', 'pa', "Panjabi; Punjabi", "pendjabi" ),
         ( 'pap', None, "Papiamento", "papiamento" ),
         ( 'pau', None, "Palauan", "palau" ),
         ( 'peo', None, "Persian, Old (ca.600-400 B.C.)", "perse, vieux (ca. 600-400 av. J.-C.)" ),
         ( 'per', 'fa', "Persian", "persan" ),
         ( 'phi', None, "Philippine languages", "philippines, langues" ),
         ( 'phn', None, "Phoenician", "phénicien" ),
         ( 'pli', 'pi', "Pali", "pali" ),
         ( 'pol', 'pl', "Polish", "polonais" ),
         ( 'pon', None, "Pohnpeian", "pohnpei" ),
         ( 'por', 'pt', "Portuguese", "portugais" ),
         ( 'pra', None, "Prakrit languages", "prâkrit, langues" ),
         ( 'pro', None, "Provençal, Old (to 1500);Occitan, Old (to 1500)", "provençal ancien (jusqu'à 1500); occitan ancien (jusqu'à 1500)" ),
         ( 'pus', 'ps', "Pushto; Pashto", "pachto" ),
         ( 'que', 'qu', "Quechua", "quechua" ),
         ( 'raj', None, "Rajasthani", "rajasthani" ),
         ( 'rap', None, "Rapanui", "rapanui" ),
         ( 'rar', None, "Rarotongan; Cook Islands Maori", "rarotonga; maori des îles Cook" ),
         ( 'roa', None, "Romance languages", "romanes, langues" ),
         ( 'roh', 'rm', "Romansh", "romanche" ),
         ( 'rom', None, "Romany", "tsigane" ),
         ( 'rum', 'ro', "Romanian; Moldavian; Moldovan", "roumain; moldave" ),
         ( 'rum', 'ro', "Romanian; Moldavian; Moldovan", "roumain; moldave" ),
         ( 'run', 'rn', "Rundi", "rundi" ),
         ( 'rup', None, "Aromanian; Arumanian; Macedo-Romanian", "aroumain; macédo-roumain" ),
         ( 'rus', 'ru', "Russian", "russe" ),
         ( 'sad', None, "Sandawe", "sandawe" ),
         ( 'sag', 'sg', "Sango", "sango" ),
         ( 'sah', None, "Yakut", "iakoute" ),
         ( 'sai', None, "South American Indian languages", "sud-amérindiennes, langues" ),
         ( 'sal', None, "Salishan languages", "salishennes, langues" ),
         ( 'sam', None, "Samaritan Aramaic", "samaritain" ),
         ( 'san', 'sa', "Sanskrit", "sanskrit" ),
         ( 'sas', None, "Sasak", "sasak" ),
         ( 'sat', None, "Santali", "santal" ),
         ( 'scn', None, "Sicilian", "sicilien" ),
         ( 'sco', None, "Scots", "écossais" ),
         ( 'sel', None, "Selkup", "selkoupe" ),
         ( 'sem', None, "Semitic languages", "sémitiques, langues" ),
         ( 'sga', None, "Irish, Old (to 900)", "irlandais ancien (jusqu'à 900)" ),
         ( 'sgn', None, "Sign Languages", "langues des signes" ),
         ( 'shn', None, "Shan", "chan" ),
         ( 'sid', None, "Sidamo", "sidamo" ),
         ( 'sin', 'si', "Sinhala; Sinhalese", "singhalais" ),
         ( 'sio', None, "Siouan languages", "sioux, langues" ),
         ( 'sit', None, "Sino-Tibetan languages", "sino-tibétaines, langues" ),
         ( 'sla', None, "Slavic languages", "slaves, langues" ),
         ( 'slo', 'sk', "Slovak", "slovaque" ),
         ( 'slo', 'sk', "Slovak", "slovaque" ),
         ( 'slv', 'sl', "Slovenian", "slovène" ),
         ( 'sma', None, "Southern Sami", "sami du Sud" ),
         ( 'sme', 'se', "Northern Sami", "sami du Nord" ),
         ( 'smi', None, "Sami languages", "sames, langues" ),
         ( 'smj', None, "Lule Sami", "sami de Lule" ),
         ( 'smn', None, "Inari Sami", "sami d'Inari" ),
         ( 'smo', 'sm', "Samoan", "samoan" ),
         ( 'sms', None, "Skolt Sami", "sami skolt" ),
         ( 'sna', 'sn', "Shona", "shona" ),
         ( 'snd', 'sd', "Sindhi", "sindhi" ),
         ( 'snk', None, "Soninke", "soninké" ),
         ( 'sog', None, "Sogdian", "sogdien" ),
         ( 'som', 'so', "Somali", "somali" ),
         ( 'son', None, "Songhai languages", "songhai, langues" ),
         ( 'sot', 'st', "Sotho, Southern", "sotho du Sud" ),
         ( 'spa', 'es', "Spanish; Castilian", "espagnol; castillan" ),
         ( 'alb', 'sq', "Albanian", "albanais" ),
         ( 'srd', 'sc', "Sardinian", "sarde" ),
         ( 'srn', None, "Sranan Tongo", "sranan tongo" ),
         ( 'srp', 'sr', "Serbian", "serbe" ),
         ( 'srr', None, "Serer", "sérère" ),
         ( 'ssa', None, "Nilo-Saharan languages", "nilo-sahariennes, langues" ),
         ( 'ssw', 'ss', "Swati", "swati" ),
         ( 'suk', None, "Sukuma", "sukuma" ),
         ( 'sun', 'su', "Sundanese", "soundanais" ),
         ( 'sus', None, "Susu", "soussou" ),
         ( 'sux', None, "Sumerian", "sumérien" ),
         ( 'swa', 'sw', "Swahili", "swahili" ),
         ( 'swe', 'sv', "Swedish", "suédois" ),
         ( 'syc', None, "Classical Syriac", "syriaque classique" ),
         ( 'syr', None, "Syriac", "syriaque" ),
         ( 'tah', 'ty', "Tahitian", "tahitien" ),
         ( 'tai', None, "Tai languages", "tai, langues" ),
         ( 'tam', 'ta', "Tamil", "tamoul" ),
         ( 'tat', 'tt', "Tatar", "tatar" ),
         ( 'tel', 'te', "Telugu", "télougou" ),
         ( 'tem', None, "Timne", "temne" ),
         ( 'ter', None, "Tereno", "tereno" ),
         ( 'tet', None, "Tetum", "tetum" ),
         ( 'tgk', 'tg', "Tajik", "tadjik" ),
         ( 'tgl', 'tl', "Tagalog", "tagalog" ),
         ( 'tha', 'th', "Thai", "thaï" ),
         ( 'tib', 'bo', "Tibetan", "tibétain" ),
         ( 'tig', None, "Tigre", "tigré" ),
         ( 'tir', 'ti', "Tigrinya", "tigrigna" ),
         ( 'tiv', None, 'Tiv', 'tiv' ),
         ( 'tkl', None, "Tokelau", "tokelau" ),
         ( 'tlh', None, "Klingon; tlhIngan-Hol", "klingon" ),
         ( 'tli', None, "Tlingit", "tlingit" ),
         ( 'tmh', None, "Tamashek", "tamacheq" ),
         ( 'tog', None, "Tonga (Nyasa)", "tonga (Nyasa)" ),
         ( 'ton', 'to', "Tonga (Tonga Islands)", "tongan (Îles Tonga)" ),
         ( 'tpi', None, "Tok Pisin", "tok pisin" ),
         ( 'tsi', None, "Tsimshian", "tsimshian" ),
         ( 'tsn', 'tn', "Tswana", "tswana" ),
         ( 'tso', 'ts', "Tsonga", "tsonga" ),
         ( 'tuk', 'tk', "Turkmen", "turkmène" ),
         ( 'tum', None, "Tumbuka", "tumbuka" ),
         ( 'tup', None, "Tupi languages", "tupi, langues" ),
         ( 'tur', 'tr', "Turkish", "turc" ),
         ( 'tut', None, "Altaic languages", "altaïques, langues" ),
         ( 'tvl', None, "Tuvalu", "tuvalu" ),
         ( 'twi', 'tw', 'Twi', 'twi' ),
         ( 'tyv', None, "Tuvinian", "touva" ),
         ( 'udm', None, "Udmurt", "oudmourte" ),
         ( 'uga', None, "Ugaritic", "ougaritique" ),
         ( 'uig', 'ug', "Uighur; Uyghur", "ouïgour" ),
         ( 'ukr', 'uk', "Ukrainian", "ukrainien" ),
         ( 'umb', None, "Umbundu", "umbundu" ),
         ( 'und', None, "Undetermined", "indéterminée" ),
         ( 'urd', 'ur', "Urdu", "ourdou" ),
         ( 'uzb', 'uz', "Uzbek", "ouszbek" ),
         ( 'vai', None, 'Vai', 'vaï' ),
         ( 'ven', 've', "Venda", "venda" ),
         ( 'vie', 'vi', "Vietnamese", "vietnamien" ),
         ( 'vol', 'vo', "Volapük", "volapük" ),
         ( 'vot', None, "Votic", "vote" ),
         ( 'wak', None, "Wakashan languages", "wakashanes, langues" ),
         ( 'wal', None, "Wolaitta; Wolaytta", "wolaitta; wolaytta" ),
         ( 'war', None, "Waray", "waray" ),
         ( 'was', None, "Washo", "washo" ),
         ( 'wel', 'cy', "Welsh", "gallois" ),
         ( 'wen', None, "Sorbian languages", "sorabes, langues" ),
         ( 'wln', 'wa', "Walloon", "wallon" ),
         ( 'wol', 'wo', "Wolof", "wolof" ),
         ( 'xal', None, "Kalmyk; Oirat", "kalmouk; oïrat" ),
         ( 'xho', 'xh', "Xhosa", "xhosa" ),
         ( 'yao', None, 'Yao', 'yao' ),
         ( 'yap', None, "Yapese", "yapois" ),
         ( 'yid', 'yi', "Yiddish", "yiddish" ),
         ( 'yor', 'yo', "Yoruba", "yoruba" ),
         ( 'ypk', None, "Yupik languages", "yupik, langues" ),
         ( 'zap', None, "Zapotec", "zapotèque" ),
         ( 'zbl', None, "Blissymbols; Blissymbolics; Bliss", "symboles Bliss; Bliss" ),
         ( 'zen', None, "Zenaga", "zenaga" ),
         ( 'zgh', None, "Standard Moroccan Tamazight", "amazighe standard marocain" ),
         ( 'zha', 'za', "Zhuang; Chuang", "zhuang; chuang" ),
         ( 'chi', 'zh', "Chinese", "chinois" ),
         ( 'znd', None, "Zande languages", "zandé, langues" ),
         ( 'zul', 'zu', "Zulu", "zoulou" ),
         ( 'zun', None, "Zuni", "zuni" ),
         ( 'zxx', None, "No linguistic content; Not applicable", "pas de contenu linguistique; non applicable" ),
         ( 'zza', None, "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki", "zaza; dimili; dimli; kirdki; kirmanjki; zazaki" ),
)

class Lang:
    def __init__(self, tup):
        self.long_code    = tup[0]
        self.short_code   = tup[1]
        self.english_name = tup[2]
        self.french_name  = tup[3]

LANG_LIST = [ Lang(x) for x in LANGS ]

LANG_MAP = dict([(x.long_code, x) for x in LANG_LIST])
LANG_MAP.update(dict([(x.short_code, x) for x in LANG_LIST]))

def is_valid_lang(val):
    return str(val).strip() in LANG_MAP


def lang_english_name(code):
    lang = lang_by_code(code)
    if lang: return lang.english_name


def lang_by_code(code):
    return LANG_MAP.get(code.lower())
